spawnemnu.category.core=C.O.R.E.

// Scoreboard
core.scoreboard.links.addons=Аддоны
core.scoreboard.links.github=GitHub

core.scoreboard.info.map=Карта
core.scoreboard.info.players=Игроки
core.scoreboard.info.uptime=UpTime
core.scoreboard.info.tps=TPS
core.scoreboard.info.tps.tip=Ticks Per Second\nКоличество тиков, обрабатываемых сервером в течение одной секунды.
core.scoreboard.info.entities=Энтити
core.scoreboard.info.entities.tip=Количество всех сущностей (Entity), существующих на клиенте.

core.scoreboard.player.nick=Никнейм
core.scoreboard.player.gamemode=Режим игры
core.scoreboard.player.ping=Пинг

// Map Tags
maptag.snow=Снег
maptag.day=День
maptag.night=Ночь