spawnemnu.category.core=C.O.R.E.

// Scoreboard
core.scoreboard.links.addons=Addons
core.scoreboard.links.github=GitHub

core.scoreboard.info.map=Map
core.scoreboard.info.players=Players
core.scoreboard.info.uptime=UpTime
core.scoreboard.info.tps=TPS
core.scoreboard.info.tps.tip=Ticks Per Second.
core.scoreboard.info.entities=Entities
core.scoreboard.info.entities.tip=Amount of entities exists on client side.

core.scoreboard.player.nick=Nick
core.scoreboard.player.gamemode=Game Mode
core.scoreboard.player.ping=Ping

// Map Tags
core.maptag.snow=Snow
core.maptag.day=Day
core.maptag.night=Night