// Spawnemnu
spawnemnu.category.core=C.O.R.E.

// Tool - NeoWeld
tool.neoweld.name=NeoWeld
tool.neoweld.desc=Weld multiple objects at once, optimally
tool.neoweld.left=Select or deselect objects
tool.neoweld.left_use=Select objects in range
tool.neoweld.right=Weld selected objects to each other
tool.neoweld.right_use=Weld selected objects to world
tool.neoweld.reload=Clear selection

tool.neoweld.do_weld=Weld props
tool.neoweld.do_nocollide=No-collide props
tool.neoweld.select_radius=Multi-select radius
tool.neoweld.bound_scale=Scale for pair detection

// Tool - Unbreakable
tool.unbreakable.name=Unbreakable
tool.unbreakable.desc=Makes objects unbreakable
tool.unbreakable.left=Make an object unbreakable
tool.unbreakable.right=Restore object's previous settings
tool.unbreakable.reload=Make the object and everything constrained to it unbreakable

// Settings
core.settings.category.thirdperson=Thirdperson
core.settings.category.performant_render=Performant Render
core.settings.category.smooth_noclip=Smooth Noclip
core.settings.category.mute_toolgun=Toolgun Mute

core.settings.enabled=Enabled

core.settings.smooth_noclip_crouch_default=Default crouch
core.settings.cl_toolgun_sound=Sound
core.settings.cl_toolgun_effects=Effects

// Scoreboard
core.scoreboard.links.addons=Addons
core.scoreboard.links.github=GitHub

core.scoreboard.info.map=Map
core.scoreboard.info.players=Players
core.scoreboard.info.uptime=UpTime
core.scoreboard.info.tps=TPS
core.scoreboard.info.tps.tip=Ticks Per Second.
core.scoreboard.info.entities=Entities
core.scoreboard.info.entities.tip=Amount of entities exists on client side.

core.scoreboard.player.nick=Nick
core.scoreboard.player.gamemode=Game Mode
core.scoreboard.player.ping=Ping

// Map Tags
core.maptag.snow=Snow
core.maptag.day=Day
core.maptag.night=Night